services:
  api:
    command: poetry run uvicorn api_server.main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
    environment:
      IS_PROD: false
      PYTHONPATH: /app/src
